import {
  bmw,
  kona,
  mercides,
  logo,
  maclaren,
  mustang,
  mazda,
  tiguan,
  profile,
  bmw1,
  bmw2,
  bmw3,
  bmw4,
  kona2,
  kona3,
  kona4,
  kona5,
  kona6,
  kona7,
  mer2,
  mer3,
  mer4,
  mustang2,
  mustang3,
  mustang4,
  tiguan4,
  tiguan2,
  tiguan3,
} from "./index.js";

const cars = [
  {
    name: "BMW",
    model: "2022",
    image: bmw,
    price: 122,
    details:
      "BMW Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [bmw, bmw1, bmw2, bmw3, bmw4],
    available: 2,
    isRented: false,
  },
  {
    name: "Kona",
    model: "2018",
    image: kona,
    price: 100,
    details:
      "Kona Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [kona, kona2, kona3, kona4, kona5, kona5, kona6, kona7],
    available: 2,
    isRented: false,
  },
  {
    name: "Mercides",
    model: "2023",
    image: mercides,
    price: 97,
    details:
      "Mericdes Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [mercides, mer2, mer3, mer4],
    available: 2,
    isRented: false,
  },
  {
    name: "Mclaren",
    model: "2024",
    image: maclaren,
    price: 77,
    details:
      "Mclaren Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [kona, mercides, mazda],
    available: 2,
    isRented: false,
  },
  {
    name: "Mustang",
    model: "2021",
    image: mustang,
    price: 200,
    details:
      "Mustang Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [mustang, mustang2, mustang3, mustang4],
    available: 2,
    isRented: false,
  },
  {
    name: "Mazda",
    model: "2007",
    image: mazda,
    price: 40,
    details:
      "Mazda Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [kona, mercides, mazda],
    available: 2,
    isRented: false,
  },
  {
    name: "Tiguan",
    model: "2024",
    image: tiguan,
    price: 50,
    details:
      "Tiguan Vision Neue Klasse X: More than just a single carthe Neue Klasse stands for a family of vehicles and for the next generation of all-electric BMW models. The BMW Vision Neue Klasse X transfers the philosophy and technology of the Neue Klasse to a pioneering Sports Activity Vehicle. A first glimpse into the future.",
    sideViewImages: [tiguan, tiguan2, tiguan3, tiguan4],
    available: 2,
    isRented: false,
  },
];

export { cars };
